server:
  port: 8080


spring:
  h2:
    console:
      enabled: true   # 启用H2 Web控制台
      path: /h2-console  # 控制台访问路径
  datasource:
    url: jdbc:h2:mem:testdb  # 内存模式数据库
    driver-class-name: org.h2.Driver
    username: sa
    password: ""  # 密码留空

