services:
  file:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    container_name: minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /Users/jiaxiaopeng/docker/minio/data:/data
    environment:
      - MINIO_ACCESS_KEY=myminioadmin
      - MINIO_SECRET_KEY=myminioadmin
    command: server /data --console-address ":9001"
  search:
    image: getmeili/meilisearch:v1.15
    container_name: meili
    restart: unless-stopped
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY=R5T5WDon_QrPqhFK97NgGlTVa81iuVlN44TMLiClTTg
    volumes:
      - /Users/jiaxiaopeng/docker/meili/data:/meili_data
  cache:
    image: redis:7.2.6
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=admin1234
  db:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - /Users/jiaxiaopeng/docker/mysql8/data:/var/lib/mysql
      - /Users/jiaxiaopeng/docker/mysql8/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin123456
      - MYSQL_DATABASE=kit
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      