networks:
  mynet:
    driver: bridge
services:
  file:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    container_name: minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /Users/jiaxiaopeng/docker/minio/data:/data
    environment:
      - MINIO_ACCESS_KEY=myminioadmin
      - MINIO_SECRET_KEY=myminioadmin
    networks:
      - mynet
    command: server /data --console-address ":9001"
  search:
    image: getmeili/meilisearch:v1.15
    container_name: meili
    restart: unless-stopped
    ports:
      - 7700:7700
    networks:
      - mynet
    environment:
      - MEILI_MASTER_KEY=R5T5WDon_QrPqhFK97NgGlTVa81iuVlN44TMLiClTTg
    volumes:
      - /Users/jiaxiaopeng/docker/meili/data:/meili_data
  cache:
    image: redis:7.2.6
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - mynet
    environment:
      - REDIS_PASSWORD=admin1234
  db:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - mynet
    volumes:
      - /Users/jiaxiaopeng/docker/mysql8/data:/var/lib/mysql
      - /Users/jiaxiaopeng/docker/mysql8/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin123456
      - MYSQL_DATABASE=kit
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  musicn:
    image: ghcr.io/wy580477/musicn-container:latest
    container_name: musicn
    restart: unless-stopped
    networks:
      - mynet
    entrypoint: ["/sbin/tini", "--", "msc", "-q"]
    ports:
      - "7478:7478"
    volumes:
      - /Users/jiaxiaopeng/Music:/data

  pairdrop:
    image: linuxserver/pairdrop:latest
    container_name: pairdrop
    restart: unless-stopped
    networks:
      - mynet
    ports:
      - 3049:3000
    environment:
      - PUID=1000
      - PGID=1000
      - WS_FALLBACK=true
      - TZ=Asia/Shanghai

  readeck:
    image: codeberg.org/readeck/readeck:latest
    container_name: readeck
    restart: unless-stopped
    ports:
      - 8792:8000
    networks:
      - mynet
    volumes:
      - ./data:/readeck

  gohttpserver:
    image: codeskyblue/gohttpserver
    container_name: gohttpserver
    restart: unless-stopped
    ports:
      - "7050:8000"
    networks:
      - mynet
    volumes:
      - /Users/jiaxiaopeng/data:/app/public
    command:
      - --upload
      - --delete
      - --auth-type=http
      - --auth-http=admin1234:admin1234

  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    restart: always
    ports:
      - 8213:80
    networks:
      - mynet
    volumes:
      - /你的路径/config:/app/data/config
      - /你的路径/data:/app/data/db
      - /你的路径/images:/app/data/images:ro
      - /你的路径/tmp:/app/data/tmp
    environment:
      - NODE_ENV=production