CREATE TABLE `session`
(
    `aid`                       BIGINT(20)   NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `sid`                       VARCHAR(255) NOT NULL COMMENT '会话ID（对外暴露）',
    `robot_id`                  VARCHAR(255)          DEFAULT NULL COMMENT '机器人ID',
    `app_id`                    VARCHAR(255)          DEFAULT NULL COMMENT '消息号ID',
    `session_type`              VARCHAR(50)           DEFAULT NULL COMMENT '会话类型（bot,manual）',
    `session_state`             VARCHAR(50)           DEFAULT NULL COMMENT '会话状态：bot机器人, queue=排队, manualChat=人工,end=结束',
    `user_id`                   VARCHAR(255)          DEFAULT NULL COMMENT '用户ID',
    `tenant_id`                 VARCHAR(255)          DEFAULT NULL COMMENT '租户ID',
    `target_type`               VARCHAR(50)           DEFAULT NULL COMMENT '服务媒介类型（如groupTag,helpGroup）',
    `target_id`                 VARCHAR(255)          DEFAULT NULL COMMENT '服务媒介ID（如groupId）',
    `group_id`                  VARCHAR(255)          DEFAULT NULL COMMENT '客服组或技能队列ID',
    `assitant_id`               VARCHAR(255)          DEFAULT NULL COMMENT '客服ID',
    `extra`                     TEXT COMMENT '会话额外信息（JSON格式）',
    `session_from`              VARCHAR(50)           DEFAULT NULL COMMENT '会话来源：userToManual/userConfirm, manualToUser, forward',
    `session_receive_type`      VARCHAR(50)           DEFAULT NULL COMMENT '客服接收类型：autoDistribute, manualClaim',
    `before_session_id`         VARCHAR(255)          DEFAULT NULL COMMENT '转接前的会话ID',
    `create_time`               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`               DATETIME              DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
    `session_last_time`         DATETIME              DEFAULT NULL COMMENT '会话最后有效时间',
    `session_end_time`          DATETIME              DEFAULT NULL COMMENT '会话结束时间',
    `cause`                     VARCHAR(50)           DEFAULT NULL COMMENT '结束原因：客服关闭, 用户关闭, 用户超时, 客服超时, 转接关闭, 排队超时',
    `session_queue_time`        DATETIME              DEFAULT NULL COMMENT '开始排队时间',
    `session_manual_time`       DATETIME              DEFAULT NULL COMMENT '开始人工时间',
    `take_over_time`            DATETIME              DEFAULT NULL COMMENT '客服认领时间',
    `session_first_message_id`  VARCHAR(255)          DEFAULT NULL COMMENT '会话第一条消息ID',
    `session_end_message_id`    VARCHAR(255)          DEFAULT NULL COMMENT '会话结束消息ID',
    `user_fist_message_id`      VARCHAR(255)          DEFAULT NULL COMMENT '用户第一条消息ID',
    `user_fist_message_time`    DATETIME              DEFAULT NULL COMMENT '用户第一条消息时间',
    `user_last_message_id`      VARCHAR(255)          DEFAULT NULL COMMENT '用户最后一条消息ID',
    `user_last_message_time`    DATETIME              DEFAULT NULL COMMENT '用户最后一条消息时间',
    `user_request_robot_num`    INT(11)               DEFAULT 0 COMMENT '用户提问机器人次数',
    `user_request_manual_num`   INT(11)               DEFAULT 0 COMMENT '用户提问人工次数',
    `user_request`              TINYINT(1)            DEFAULT 0 COMMENT '用户未提问人工（转人工后）',
    `manual_first_message_id`   VARCHAR(255)          DEFAULT NULL COMMENT '客服第一条消息ID',
    `manual_first_message_time` DATETIME              DEFAULT NULL COMMENT '客服第一条回复时间',
    `manual_last_message_id`    VARCHAR(255)          DEFAULT NULL COMMENT '客服最后一条消息ID',
    `manual_last_message_time`  DATETIME              DEFAULT NULL COMMENT '客服最后一条回复时间',
    `manual_reply_num`          INT(11)               DEFAULT 0 COMMENT '客服回复次数',
    `manual_reply`              TINYINT(1)            DEFAULT 0 COMMENT '客服未回复（人工会话）',
    PRIMARY KEY (`aid`),
    UNIQUE KEY `idx_sid` (`sid`),
    KEY `idx_user_id_app_id` (`user_id`, `app_id`),
    KEY `idx_user_id_app_id` (`assitant_id`, `session_state`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='会话信息表';
