server:
  port: 8081
  servlet:
    context-path: /app/api
spring:
  profiles:
    active: dev
custom:
  log:
    pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{90} - %msg%n"
    dir: kit-app

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

easy-es:
  # 是否开启EE自动配置
  enable: true
  # ES连接地址+端口
  address: localhost:9200
  # 关闭自带banner
  banner: false
