server:
  port: 8080
  servlet:
    context-path: /core/api
spring:
  profiles:
    active: dev
  elasticsearch:
    uris: http://localhost:9200
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      config:
        server-addr: http://127.0.0.1:8848
      discovery:
        server-addr: http://127.0.0.1:8848
      server-addr: http://127.0.0.1:8848

custom:
  log:
    pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{90} - %msg%n"
    dir: kit-core

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

jedis:
  enable: false

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    # 输出es的查询参数(调试用)
    tracer: TRACE
