server:
  port: 8080
  servlet:
    context-path: /demo/api
spring:
  profiles:
    active: dev
custom:
  log:
    pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{90} - %msg%n"
    dir: demo-app

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

